version: '3.4'
networks:
   capstone-api-network:
services:
 capstonedb:
     container_name: capstonedb
     image: mcr.microsoft.com/mssql/server:2019-latest
     restart: unless-stopped
     environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=MinhQuan@2002
     networks :
        - capstone-api-network
     ports:
        - 1431:1433
 cachedb:
      container_name: cachedb
      image: redis:latest
      volumes:
        - "./MobileAPI/RedisConfig:/usr/local/etc/redis"
      ports:
         - 6379:6379
      networks :
        - capstone-api-network
      environment:
         - REDIS_PASSWORD=MinhQuan@123
      command: /bin/sh -c "redis-server --requirepass MinhQuan@123"
 mobileapi:
    image: ${DOCKER_REGISTRY-}mobileapi
    build:
      context: .
      dockerfile: APIs/MobileAPI/Dockerfile
    ports:
        - 8024:80  
        - 7777:443  
    networks:
      - capstone-api-network
 webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: APIs/WebAPI/Dockerfile
    ports:
        - 7024:80  
        - 9999:443
    networks:
      - capstone-api-network
   
